Movie.delete_all


# #20 gêneros
# Genre.create(name: "Terror")
# Genre.create(name: "Suspense")
# Genre.create(name: "Romance")
# Genre.create(name: "Documentário")
# Genre.create(name: "Biografia")
# Genre.create(name: "Histórico")
# Genre.create(name: "Musical")
# Genre.create(name: "Guerra")
# Genre.create(name: "Western")
# Genre.create(name: "Policial")
# Genre.create(name: "Espionagem")
# Genre.create(name: "Animação")
# Genre.create(name: "Esporte")
# Genre.create(name: "Família")
# Genre.create(name: "Ação")
# Genre.create(name: "Aventura")
# Genre.create(name: "Comédia")
# Genre.create(name: "Drama")
# Genre.create(name: "Fantasia")
# Genre.create(name: "Ficção Científica")

# # 20 Diretores
# Director.create(name: "Steven Spielberg", nationality: "Americano", birth_date: Date.new(1946, 12, 18), favorite_genre_id: 25)
# Director.create(name: "Hayao Miyazaki", nationality: "Japonês", birth_date: Date.new(1941, 1, 5), favorite_genre_id: 26)
# Director.create(name: "Pedro Almodóvar", nationality: "Espanhol", birth_date: Date.new(1949, 9, 25), favorite_genre_id: 27)
# Director.create(name: "Guillermo del Toro", nationality: "Mexicano", birth_date: Date.new(1964, 10, 9), favorite_genre_id: 28)
# Director.create(name: "Christopher Nolan", nationality: "Britânico", birth_date: Date.new(1970, 7, 30), favorite_genre_id: 29)
# Director.create(name: "Bong Joon-ho", nationality: "Sul-coreano", birth_date: Date.new(1969, 9, 14), favorite_genre_id: 30)
# Director.create(name: "Jane Campion", nationality: "Neozelandesa", birth_date: Date.new(1954, 4, 30), favorite_genre_id: 31)
# Director.create(name: "Ang Lee", nationality: "Taiwanês", birth_date: Date.new(1954, 10, 23), favorite_genre_id: 32)
# Director.create(name: "Jean-Pierre Jeunet", nationality: "Francês", birth_date: Date.new(1953, 9, 3), favorite_genre_id: 33)
# Director.create(name: "Fatih Akin", nationality: "Alemão", birth_date: Date.new(1973, 8, 25), favorite_genre_id: 34)
# Director.create(name: "Nuri Bilge Ceylan", nationality: "Turco", birth_date: Date.new(1959, 1, 26), favorite_genre_id: 35)
# Director.create(name: "Asghar Farhadi", nationality: "Iraniano", birth_date: Date.new(1972, 5, 7), favorite_genre_id: 36)
# Director.create(name: "Yorgos Lanthimos", nationality: "Grego", birth_date: Date.new(1973, 5, 27), favorite_genre_id: 37)
# Director.create(name: "Paweł Pawlikowski", nationality: "Polonês", birth_date: Date.new(1957, 9, 15), favorite_genre_id: 38)
# Director.create(name: "Andrey Zvyagintsev", nationality: "Russo", birth_date: Date.new(1964, 2, 6), favorite_genre_id: 39)
# Director.create(name: "Lars von Trier", nationality: "Dinamarquês", birth_date: Date.new(1956, 4, 30), favorite_genre_id: 40)
# Director.create(name: "Wong Kar-wai", nationality: "Hong Kong", birth_date: Date.new(1956, 7, 17), favorite_genre_id: 41)
# Director.create(name: "Abdellatif Kechiche", nationality: "Tunisiano", birth_date: Date.new(1960, 12, 7), favorite_genre_id: 42)
# Director.create(name: "Alejandro González Iñárritu", nationality: "Mexicano", birth_date: Date.new(1963, 8, 15), favorite_genre_id: 43)
# Director.create(name: "Alfonso Cuarón", nationality: "Mexicano", birth_date: Date.new(1961, 11, 28), favorite_genre_id: 44)
